// NEON RECALL string table {key: [zh-HK, en]} — cyber-kit v0.2.1 i18n.
import { i18n } from 'cyber-kit';
i18n.add({
  'doc.title': ['霓虹記憶 NEON RECALL · 賽博朋克 3D 記憶配對', 'NEON RECALL · cyberpunk 3D memory match'],
  score: ['分數', 'SCORE'], best: ['最高分', 'BEST'], level: ['關卡', 'LEVEL'], combo: ['連擊', 'COMBO'], pairs: ['配對', 'PAIRS'],
  peek: ['透視', 'PEEK'], peekS: ['PEEK · Z', 'Z'], peekTip: ['透視 (Z)', 'Peek (Z)'],
  restartTip: ['重玩此關 (R)', 'Restart level (R)'], pauseTip: ['暫停 (P / Esc)', 'Pause (P / Esc)'], muteTip: ['靜音 (M)', 'Mute (M)'],
  title: ['霓虹記憶', 'NEON RECALL'], titleEn: ['NEON RECALL', '霓虹記憶'],
  tagline: ['翻開霓虹卡牌，記住圖案，兩兩配對。<br>冇時間限制、冇得輸 —— 關卡無盡，越記越多星。', 'Flip the neon cards, remember the icons, match the pairs.<br>No timer, no losing — endless levels, collect every star.'],
  continue: ['繼續', 'CONTINUE'], continueS: ['第 {level} 關 · {score} 分', 'LEVEL {level} · {score} PTS'],
  start: ['開始遊戲', 'START'], startS: ['START · ENTER', 'ENTER'],
  touchHint: ['手機：直接點卡牌翻開', 'Touch: tap a card to flip it'],
  keysHint: ['滑鼠點擊 / <kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> 揀卡 <kbd>Enter</kbd> 翻開　<kbd>Z</kbd> 透視　<kbd>P</kbd> 暫停　<kbd>M</kbd> 靜音', 'Click / <kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> select <kbd>Enter</kbd> flip　<kbd>Z</kbd> peek　<kbd>P</kbd> pause　<kbd>M</kbd> mute'],
  bestLevel: ['最遠關卡（無盡紀錄）', 'ENDLESS BEST LEVEL'], stars: ['星星', 'STARS'],
  pausedS: ['PAUSED', '已暫停'], saved: ['關卡進度已儲存', 'progress saved'],
  synced: ['記憶同步', 'SYNCED'], syncedS: ['SYNCED', '記憶同步'],
  levelScore: ['本關得分', 'LEVEL SCORE'], misses: ['失誤', 'MISSES'], maxCombo: ['最高連擊', 'MAX COMBO'], time: ['用時', 'TIME'],
  next: ['下一關', 'NEXT LEVEL'], nextS: ['NEXT · ENTER', 'ENTER'], replay: ['再玩此關', 'REPLAY'], replayS: ['爭取三星', 'go for 3 stars'],
  levelN: ['第 {n} 關', 'LEVEL {n}'], memorise: ['記住佢哋！', 'MEMORISE!'],
  glitch: ['⚠ 數據錯亂！兩張卡互換咗位置', '⚠ GLITCH! Two cards swapped places'],
  peekMoreQ: ['補充 {n} 次透視？', 'Refill {n} peeks?'], peekMore: ['補充 {n} 次透視', 'Refill {n} peeks'],
  peekAdText: ['睇一段自願觀看嘅獎勵廣告即可補充。唔睇都可以照玩。', 'Watch an optional rewarded ad to refill. You can keep playing without it.'],
  peekFreeText: ['網頁版免費補充。(App 版會用自願觀看嘅獎勵廣告。)', 'Free on the web. (The app uses an optional rewarded ad.)'],
  claim: ['領取', 'CLAIM'], noReward: ['冇攞到獎勵', 'No reward'], peekPlus: ['透視 +1', 'PEEK +1'],
  clearKicker: ['第 {n} 關完成 · +{bonus} ★', 'LV {n} CLEAR · +{bonus} ★'],
  restartQ: ['重玩此關？', 'Restart this level?'], restartText: ['今關得分會清除。', 'This level\'s score will be cleared.'], restart: ['重玩', 'RESTART'], keepPlaying: ['繼續玩', 'KEEP PLAYING'],
  endless: ['無盡', 'ENDLESS'],
  milestone: ['里程碑：第 {n} 關！', 'MILESTONE: LEVEL {n}!'], milestoneS: ['+{pts} 分 · 透視 +{peeks} · 新區域', '+{pts} · PEEK +{peeks} · NEW DISTRICT'],
  fatal: ['載入失敗', 'Failed to start'],
  'icon.chip': ['晶片', 'CHIP'], 'icon.bolt': ['閃電', 'BOLT'], 'icon.eye': ['電子眼', 'CYBER EYE'], 'icon.cat': ['機械貓', 'ROBO CAT'],
  'icon.lantern': ['燈籠', 'LANTERN'], 'icon.ramen': ['拉麵', 'RAMEN'], 'icon.rocket': ['火箭', 'ROCKET'], 'icon.heart': ['霓虹心', 'NEON HEART'],
  'icon.planet': ['行星', 'PLANET'], 'icon.crystal': ['水晶', 'CRYSTAL'], 'icon.key': ['密鑰', 'KEY'], 'icon.note': ['音符', 'NOTE'],
  'icon.moon': ['月亮', 'MOON'], 'icon.drone': ['無人機', 'DRONE'], 'icon.tram': ['叮叮', 'DING-DING TRAM'], 'icon.umbrella': ['雨傘', 'UMBRELLA'],
});
